baseurl: /
languageCode: en-US
title: Mean,Median&Me
theme: "hugo-PaperMod"
googleAnalytics: ''
disqusShortname: ''

#enableRobotsTXT: true
#buildDrafts: false
#buildFuture: false
#buildExpired: false

#minify:
#  disableXML: true
#  minifyOutput: true

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
#permalinks:
#  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Blog
      url: /post/
    - name: Portfolio
      url: /portfolio/

params:
  env: production
  title: MeanMedian&Me
  description: A website built through Hugo and blogdown (- a work in progress).
  keywords: [Blog, Portfolio]
  images: ["https://www.google.com/url?sa=i&url=https%3A%2F%2Fa-z-animals.com%2Fanimals%2Fgoose%2F&psig=AOvVaw2m49GkWbski3VIICcMngC2&ust=1687280807109000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCKj96_roz_8CFQAAAAAdAAAAABAE"]
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  
  profileMode:
    enabled: false # needs to be explicitly set
    title: '<Title>'
    subtitle: "This is subtitle"
    imageUrl: /content/UN.jpeg/
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
     - name: Posts
       url: posts
     - name: Tags
       url: tags

  homeInfoParams:
    Title: "Welcome to Mean,Median&Me."
    Content: >
            It's a work in progress.
            
            - All data analyses and projects shared on this website were made using R, including the website itself. The data I use is also usually scraped in R.      
            
           
            - Expect to see analyses on movies and basketball analytics, but also other stuff hopefully.
    editPost:
    URL: "https://github.com/ibenchekroun/my-second-website/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  socialIcons:
   - name: twitter
     url: "https://twitter.com/"
   - name: stackoverflow
     url: "https://stackoverflow.com"
   - name: github
     url: "https://github.com/"
   - name: letterboxd
     url: "https://letterboxd.com/"

# assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
#   favicon: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.yahoo.com%2Flifestyle%2Fthink-leave-season-3-trailer-194518810.html&psig=AOvVaw1KWMKzYhL4RYQ_r7CQnQSm&ust=1687280909846000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJiwqKzpz_8CFQAAAAAdAAAAABAE"
    
label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35
#    


  # for search
  # https://fusejs.io/api/options.html
#  fuseOpts:
#    isCaseSensitive: false
#    shouldSort: true
#    location: 0
#    distance: 1000
#    threshold: 0.4
#    minMatchCharLength: 0
#    keys: ["title", "permalink", "summary", "content"]
#menu:
#  main:
#    - identifier: categories
#      name: categories
#      url: https://example.org
#      weight: 10
#    - identifier: tags
#      name: tags
#      url: https://example.org
#      weight: 20
#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#  pygmentsUseClasses: true
#markup:
#  highlight:
#    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
        
#  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
#  MathJaxVersion: 2.7.5
#  favicon: 
#  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
#  highlightjsLang:
#    - r
#    - yaml
#  highlightjsTheme: github
#  highlightjsVersion: 9.12.0
#  logo:
#    alt: Logo
#    height: 50
#    url: logo.png
#    width: 50
#  homeInfoParams:
#        Title: Hi there wave
#        Content: Can be Info, links, about...

#markup:
#  defaultMarkdownHandler: goldmark
#  goldmark:
#    renderer:
#      unsafe: yes
